[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200

lib_deps =
    knolleary/PubSubClient @ ^2.8
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
    madhephaestus/ESP32Servo @ ^3.2.1
    https://github.com/GyverLibs/FastBot.git